# Generated by Django 4.2.11 on 2024-05-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    def custom_task(self,schema_editor):
        Books =self.get_model('bookapp','Books')
        for a in Books.objects.all():
            a.title = a.title.capitalize()
            a.save()


    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(custom_task, migrations.RunPython.noop)
    ]
